{
 "title": "Dashboard – API + Prometheus + PostgreSQL",
 "tags": [
  "observabilidade",
  "api",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Requisições por Rota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (route) (http_requests_total)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "RPS – Requests por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Latência Média (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) / sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Latência Média"
    }
   ]
  },
  {
   "title": "Histograma de Latência",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_bucket[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requisições por Status Code",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (status) (http_requests_total)",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "Últimas 20 Vendas",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT categoria, valor, data_venda FROM vendas ORDER BY data_venda DESC LIMIT 20;"
    }
   ]
  },
  {
   "title": "CPU – Node.js",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "process_cpu_user_seconds_total", "legendFormat": "CPU User Time" }
   ]
  },
  {
   "title": "Uso de Memória – Node.js",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Memória" }
   ]
  }
 ]
}